# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      pip3 install neo4j      
      docker pull neo4j:4.4.8
      docker run  -d                    \
      -p 7474:7474 --publish=7687:7687  \
      --volume=$HOME/neo4j/data:/data   \
      --name neo4j-server               \
      --env NEO4J_AUTH=neo4j/tenaciousD \
      neo4j:4.4.8 
    command: |
      docker start neo4j-server
      ./instr.sh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 7474
    onOpen: ignore
    visibility: public
  - port: 7687
    visibility: public
    onOpen: ignore
    
